doFir.push(function(){var ibtmediaDfp=function(){};var adblock_status='';(function($){ibtmediaDfp=$.fn.ibtmediaDfp=$.ibtmediaDfp=function ibtmediaDfp(){if(typeof Drupal.settings.ibtmediaDfp=='undefined'){return}
var config=Drupal.settings.ibtmediaDfp;if(typeof config=='undefined'||!config){return}
this.config=config;this.inArray=function(needle,haystack){var length=haystack.length;for(var i=0;i<length;i++){if(haystack[i]==needle){return!0}}
return!1};this.getNextSlotId=function(){this.nextSlotId++;return this.nextSlotId}
this.init=function(){var initilized=(typeof this.config.initilized!='undefined'&&this.config.initilized==!0)?!0:!1;var ibtmediaDfp=this;var config=this.config;if(!initilized){$(document).on('dynamicdfp',function(event){ibtmediaDfp.debug('triggered '+event.type+' event',event);var update=!0;if(typeof event.update!='undefined'){update=event.update}
var tags=[];if(typeof event.tags!='undefined'){tags=event.tags}else{tags=$('.dfp-dynamic-tag')}
if(tags.length>0){tags.each(function(){var tag=$(this);var position=tag.data('position');if(event.positions.length>0){if(!ibtmediaDfp.inArray(position,event.positions)){return}}else{return}
ibtmediaDfp.debug('position '+position);var tagSlot=tag.data('slot');if(tagSlot!=undefined&&update==!1){return}
var wrapperId=tag.data('wrapper_id');var placeholderId=tag.data('placeholder_id')+'-adslot-'+ibtmediaDfp.getNextSlotId();tag.html('<div id="'+placeholderId+'" class="'+wrapperId+'">');if(typeof event.colorbox=='object'&&!$.isEmptyObject(event.colorbox)){var colorboxSettings={html:$('#'+placeholderId),fixed:!0,closeButton:!1,scrolling:!1};$.extend(colorboxSettings,event.colorbox);$.colorbox(colorboxSettings);ibtmediaDfp.debug('opening '+position+' tag in colorbox',placeholderId)}
var yieldbotEnabled=tag.data('yieldbot_enabled');var rubiconEnabled=tag.data('rubicon_enabled');var adunit=tag.data('adunit');var size=tag.data('size');var mappingSizes=tag.data('mapping');var position=tag.data('position');if(config.yieldbot&&yieldbotEnabled){ybotq.push(function(){googletag.cmd.push(function(){ibtmediaDfp.googletagRefresh(tag,placeholderId,adunit,size,mappingSizes,position)})})}else{googletag.cmd.push(function(){ibtmediaDfp.googletagRefresh(tag,placeholderId,adunit,size,mappingSizes,position)})}
if(config.rubicon&&rubiconEnabled){rubicontag.cmd.push(function(){ibtmediaDfp.googletagRubiconRefresh(tag,placeholderId,adunit,size,mappingSizes,position)})}})}else{ibtmediaDfp.debug('$(".dfp-dynamic-tag") tags are not found',$('.dfp-dynamic-tag'),'error')}});if(config.yieldbot){ybotq.push(function(){googletag.cmd.push(function(){ibtmediaDfp.googletagRenderEnded()})})}else{googletag.cmd.push(function(){ibtmediaDfp.googletagRenderEnded()})}
ibtmediaDfp.debug('initilized',ibtmediaDfp);initilized=!0;this.nextSlotId=0}
Drupal.settings.ibtmediaDfp.initilized=initilized;$.event.trigger({type:'ibtmediaDfpReady',ibtmediaDfp:this})};this.googletagRefresh=function(tag,placeholderId,adunit,size,mappingSizes,position){var browserSize,adSizes;var ibtmediaDfp=this;var slot=googletag.defineSlot(adunit,size,placeholderId).setTargeting("pos",position).addService(googletag.pubads());tag.data('slot',slot);if(typeof apstag!=='undefined'){var placeholderId_apstag=tag.data('placeholder_id');nw_log("apstag refresh "+placeholderId);apstag.fetchBids({slots:[{slotID:placeholderId,sizes:size}]},function(bids){apstag.setDisplayBids();googletag.pubads().refresh([slot])})}else{googletag.pubads().refresh([slot])}
ibtmediaDfp.debug('refreshing '+placeholderId,slot)},this.googletagRubiconRefresh=function(tag,placeholderId,adunit,size,mappingSizes,position){var ibtmediaDfp=this;rubicontag.defineSlot(adunit,size,placeholderId).setPosition(position).setFPI('domain',ibtmediaDfp.config.site_url);rubicontag.setTargetingForGPTSlot(googletag.slots[position])},this.googletagRenderEnded=function(){var ibtmediaDfp=this;googletag.pubads().addEventListener('slotRenderEnded',function(event){var tags=$('.dfp-dynamic-tag');if(tags.length>0){tags.each(function(){var tag=$(this);var tagSlot=tag.data('slot');if(event.slot===tagSlot){ibtmediaDfp.debug('render ended for '+tag.data('placeholder_id'),event);if($("#colorbox").length>0&&$("#colorbox").css("display")=="block"){$.colorbox.resize({innerWidth:event.size[0],innerHeight:event.size[1]})}}})}
if(event.slot===googletag.slots.adhesion){nw_log('dfp adhesion is on this page');$('html').css('padding-bottom',50)}});googletag.pubads().addEventListener('impressionViewable',function(event){var body=$('body');if(googletag.slots.top==event.slot){var obj=$('#dfp-ad-top');if(obj.hasClass('impview')&&!obj.hasClass('unstick')&&!obj.hasClass('sticky')){}}
if(googletag.slots.right1==event.slot){var obj=$('#dfp-ad-right1');if(obj.hasClass('impview')&&!obj.hasClass('unstick')&&!obj.hasClass('sticky')){}}
if(googletag.slots.right2==event.slot){var obj=$('#dfp-ad-right2');if(obj.hasClass('impview')&&!obj.hasClass('unstick')&&!obj.hasClass('sticky')){}}
if(googletag.slots.right3==event.slot){var obj=$('#dfp-ad-right3');if(obj.hasClass('impview')&&!obj.hasClass('unstick')&&!obj.hasClass('sticky')){}}
if(googletag.slots.right4==event.slot){var obj=$('#dfp-ad-right4');if(obj.hasClass('impview')&&!obj.hasClass('unstick')&&!obj.hasClass('sticky')){}}})},this.triggerDfpAd=function(positions,colorbox){$.event.trigger({type:'dynamicdfp',positions:positions,colorbox:colorbox})};this.debug=function(message,data,type){if(this.config.debug){nw_log(message);type=!type?'message':type;var prefix='%cDFP Ad: ';if(type=='message'){style='font-size: 16px; font-weight: bold; color: #002654;'}else if(type=='error'){prefix='%cDFP Ad Error: ';style='font-size: 16px; font-weight: bold; color: #e55b5b;'}
if(!data){data=''}
nw_log(prefix+message,style,data)}}
this.init()};Drupal.behaviors.ibtmediaDfp={attach:function(context,settings){if(context=='#cboxLoadedContent'){return}
var ibtdfp=new ibtmediaDfp();$('#edit-ibtmedia-dfp-dynamic-tag-test-button').click(function(){var positions=$('#edit-ibtmedia-dfp-test-ad-position').val();var ibtdfp=new ibtmediaDfp();var colorbox={};if($('#edit-ibtmedia-dfp-dynamic-tag-test-colorbox').is(':checked')){colorbox={'innerWidth':300,'innerHeight':300}}
ibtdfp.triggerDfpAd(positions,colorbox);return!1});$('#edit-ibtmedia-dfp-dynamic-tag-clear-button').click(function(){var positions=$('#edit-ibtmedia-dfp-test-ad-position').val();$(positions).each(function(){$('.dfp-ad-'+this+'-wrapper').remove()});return!1});if($('.dfp-dynamic-tag').length>0){var positions=[];var tags=[];$('.dfp-dynamic-tag').each(function(){var tag=$(this);var on_page_load=tag.data('on_page_load');var position=tag.data('position');if(on_page_load==1){positions.push(position);tags.push(tag)}});if(tags.length>0){$.event.trigger({type:'dynamicdfp',positions:positions,tags:$(tags)})}}
function sendTrackingCalls(status){adblock_status=status;if(typeof ga!='undefined'){ga('send','event','AdBlock',status,{"nonInteraction":!0,"dimension12":status})}
if(typeof dataLayer!='undefined'){dataLayer.push({'event':'AdBlock','eventCategory':'AdBlock','eventAction':status,'dimension12':status,'nonInteraction':!0})}}
var enable_blockadblock=Drupal.settings.enable_blockadblock;if(enable_blockadblock||typeof enable_blockadblock!='undefined'){if(typeof blockAdBlock==='undefined'){sendTrackingCalls('No')}else{blockAdBlock.onDetected(function(){sendTrackingCalls('Yes')});blockAdBlock.onNotDetected(function(){sendTrackingCalls('No')})}}}}}(jQuery))})